rest:
  port: 8080

grpc:
  auth:
    port: 44044
  kitchen:
    port: 44045
  
  server:
    port: 44046

  appnum: 1

repo:
  redis:
    port: 6378
    password: ""
    db: 0
  postgres:
    sslmode: "disable"
    host: "localhost"
    port: 5433
    dbname: "orders"
    username: "postgres"
  